config/about/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.blogabout, name= 'About'),
]

config/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, blogHome

urlpatterns = [
    path('post/<int:pk>/delete/', BlogDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('', BlogListView.as_view(), name='home'),
    
    path('', blogHome, name='home')
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('about/', include('about.urls')),
    path('register/', include('register.urls')),
    path('register2/', include('register2.urls')),
    
]

config/register/urls.py
from django.urls import path
from . import views
app_name =  'register'
urlpatterns = [
    path('signup/', views.signUp,  name="signup"),
    
]

config/register2/urls.py
from django.urls import path
from . import views

app_name = 'register2'

urlpatterns = [
    path('signin/', views.signIn, name='signin')
]

config/about/models.py
from django.db import models

# Create your models here.

config/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE,)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

config/register/models.py
from django.db import models

# Create your models here.
class UserDetails(models.Model):
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    email = models.EmailField()
    password1 = models.CharField(max_length=1000)
    ConfirmPasword = models.CharField(max_length=1000)

    def __str__(self):
        return self.firstname

config/register2/models.py
from django.db import models

# Create your models here.
class UserLogin(models.Model):
    username = models.CharField(max_length=200)
    password1 = models.CharField(max_length=1000)

    def __str__():
        return self.username

config/about/views.py
from django.shortcuts import render
from django.views.generic import ListView
#from .models import Post


# Create your views here.
def blogabout(request):
    context = {}
    return render(request, 'about/about.html', context)

config/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from django.urls import reverse_lazy

# Create your views here.
class BlogListView(ListView):
    model = Post
    template_name = 'blog/home.html'

def blogHome(request):
    context = {}
    return render(request, 'blog/home.html', context)

class BlogDetailView(DetailView):
    model = Post
    template_name = 'about/post_detail.html'

class BlogCreateView(CreateView): 
    model = Post    
    template_name = 'postNew/post_new.html'
    fields = ['title', 'author', 'body']

class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'edit/post_edit.html'
    fields = ['title', 'body']

class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'delete/post_delete.html'
    success_url = reverse_lazy('home')

config/register/views.py
from django.shortcuts import render,redirect
from .form import UserForm
# Create your views here.
def signUp(request):
    form = UserForm()
    if request.method == "POST":
        # firstname = request.get['firstname']
        form = UserForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('/register2/signin')
    context = {
        "form": form
    }
    return render(request, 'register/signup.html', context)
    

config/register2/views.py
from django.shortcuts import render, redirect
from .form import UserForm
# Create your views here.
def signIn(request):
    form = UserForm()
   
    context = {
        "form": form
    }
    success_url = reverse_lazy('home')

    return render(request, 'register2/signin.html', context)

config/templates/about/post_detail.html
{% extends 'base.html' %}

{% block content %}
      <div class="post-entry">
        <h2>{{post.title }}</h2>
        <p>{{post.body}}</p>
  </div>
  <a href ='{%url "post_edit" post.pk %}'> + Edit Blog Post  </a>
  <a href ='{%url "post_delete" post.pk %}'>  + Delete Blog Post</a> 
  
     
{% endblock %}

config/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" >
    <link rel ='stylesheet' href='{% static "css/base.css" %}'> 
   <title> {% block title %} {% endblock%}</title> 
</head>
<body>
    <header>
        <div class="nav-left">
            <h1><a href="{% url 'home' %}"></a>Django Blog</h1>
        </div>

        <div class="nav-right">
            <a href="{% url 'post_new' %}">New Blog Post</a>
        </div>
    
    </header>
<div>
    {% block content %}
       
    {% endblock %}
</div>
</body>
</html>

config/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Home blog</h1> 
  <p>welcome to my django blog</p>
  <a href="{% url 'register:signup' %}">SignUp Page</a>
  <a href="{% url 'register2:signin' %}">SignIn Page</a>
  <!-- {% for post in object_list %}

   <div class="post-entry">

      <h2><a href= "{% url 'post_detail' post.pk %}"> {{ post.title }}</h2>

      <p>{{post.body}}</p>

      </div>

      {% endfor %} -->
  
{% endblock %}

config/templates/delete/post_delete.html
{% extends "base.html" %}

{% block content %} 
    <h1> Delete post</h1>
    <form action=''  method='post'>
        {% csrf_token%}
        <p>Are you sure you want to delete  "{{ post.title}}"</p>
        <input type="submit" value='confire'>
    </form>

{% endblock %}

config/templates/edit/post_edit.html
{% extends "base.html" %}


{% block content %}
    <h1>Edit post   </h1>
    <form action=""  method="">
        {% csrf_token %}
        {{form.as.p}}
        <input type='submit'  value='update'>

    </form>

{% endblock %}

config/templates/postNew/post_new.html
{% extends 'base.html' %}

{% block content %}
        <h1>New post</h1>
        <form action="" method="post">
            {% csrf_token%}
            {{ form.as_p}}
            <input type='submit' value='Save'>
        </form>
{% endblock %}

config/templates/register/signup.html
{% extends 'base.html'%}


{% block title %}SignUp Page {% endblock %}
{% block content %}

<h1>SignUp Page</h1>

<form action="{% url 'register:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

config/templates/register2/signin.html
{% extends 'base.html'%}


{% block title %}SignIn Page {% endblock %}
{% block content %}

<h1>Signin Page</h1>
<form action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}